#!/usr/bin/env python3
"""Generate internal/content/seed_reviews.go from the collected Google reviews.

Selection lives here: COACH maps a review index to the coaches it names (see
BRIEF.md §4), HOME is the ordered home-page strip. Texts are copied verbatim.
Dates are approximate (Google shows "5 months ago"), resolved against the
collection date 2026-09-27.

    python3 tools/assets/gen_reviews.py && gofmt -w internal/content/seed_reviews.go
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COACH = {4: ["otar-chkadua"], 7: ["otar-chkadua"], 26: ["otar-chkadua"], 34: ["otar-chkadua"],
         1: ["vlad-zapolskikh"], 12: ["vlad-zapolskikh"], 18: ["vlad-zapolskikh"],
         5: ["evan-kostylev"], 8: ["nikolai-starodubcev"], 13: ["anastasia-novikova"],
         15: ["veriko-kundukhashvili"], 16: ["lizi-gagnidze"]}
HOME = [2, 0, 42, 11, 16, 13]


def ym(rel: str) -> str:
    m = 12 if "год" in rel else 0
    mm = re.match(r"(\d+) мес", rel)
    if mm:
        m = int(mm.group(1))
    elif rel.startswith("месяц"):
        m = 1
    y, mo = 2026, 9 - m
    while mo <= 0:
        mo += 12
        y -= 1
    return f"{y:04d}-{mo:02d}"


def lang(t: str) -> str:
    cyr = len(re.findall("[а-яА-ЯёЁ]", t))
    lat = len(re.findall("[a-zA-Z]", t))
    return "ru" if cyr > lat else "en"


def main() -> None:
    d = json.loads((ROOT / "materials/google-maps/reviews.json").read_text())
    out = ["// Code generated by tools/assets/gen_reviews.py from materials/google-maps/reviews.json. DO NOT EDIT BY HAND;",
           "// edit the selection in the generator. Texts are the authors' own words, never translated.", "",
           "package content", "",
           "// SeedReviews is the starting set: every review that names a coach, plus the",
           "// six chosen for the home page. All are real Google Maps reviews.",
           "var SeedReviews = []Review{"]
    for i in sorted(set(COACH) | set(HOME)):
        r = d[i]
        t = re.sub(r"\s*…$", "", r["text"].strip())
        coaches = "[]string{" + ", ".join(json.dumps(c) for c in COACH.get(i, [])) + "}"
        out.append('\t{ID: "g%02d", Author: %s, Lang: "%s", Rating: %d, Date: "%s", Home: %s, Sort: %d, Coaches: %s,\n\t\tText: %s},' % (
            i, json.dumps(r["name"], ensure_ascii=False), lang(t), int(r["stars"][0]), ym(r["date"]),
            "true" if i in HOME else "false", HOME.index(i) if i in HOME else 99, coaches,
            json.dumps(t, ensure_ascii=False)))
    out.append("}")
    (ROOT / "internal/content/seed_reviews.go").write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
